[project]
name = "3d-bin-packer-cpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "3d-bin-packer>=0.0.5",
    "pybind11>=2.13.6",
    "setuptools>=75.6.0",
]
